//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorreoWS
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfString", Namespace = "http://MSF232.verify/", ItemName = "string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://MSF232.verify/", ConfigurationName = "CorreoWS.WebServiceSoap")]
    public interface WebServiceSoap
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VALUES del espacio de nombres http://MSF232.verify/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_ReporteAdjunto", ReplyAction = "*")]
        CorreoWS.Enviar_ReporteAdjuntoResponse Enviar_ReporteAdjunto(CorreoWS.Enviar_ReporteAdjuntoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_ReporteAdjunto", ReplyAction = "*")]
        System.Threading.Tasks.Task<CorreoWS.Enviar_ReporteAdjuntoResponse> Enviar_ReporteAdjuntoAsync(CorreoWS.Enviar_ReporteAdjuntoRequest request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VALUES del espacio de nombres http://MSF232.verify/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_Correo", ReplyAction = "*")]
        CorreoWS.Enviar_CorreoResponse Enviar_Correo(CorreoWS.Enviar_CorreoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_Correo", ReplyAction = "*")]
        System.Threading.Tasks.Task<CorreoWS.Enviar_CorreoResponse> Enviar_CorreoAsync(CorreoWS.Enviar_CorreoRequest request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VALUES del espacio de nombres http://MSF232.verify/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_Adjuntos", ReplyAction = "*")]
        CorreoWS.Enviar_AdjuntosResponse Enviar_Adjuntos(CorreoWS.Enviar_AdjuntosRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_Adjuntos", ReplyAction = "*")]
        System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosResponse> Enviar_AdjuntosAsync(CorreoWS.Enviar_AdjuntosRequest request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VALUES del espacio de nombres http://MSF232.verify/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_AdjuntosPreview", ReplyAction = "*")]
        CorreoWS.Enviar_AdjuntosPreviewResponse Enviar_AdjuntosPreview(CorreoWS.Enviar_AdjuntosPreviewRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MSF232.verify/Enviar_AdjuntosPreview", ReplyAction = "*")]
        System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosPreviewResponse> Enviar_AdjuntosPreviewAsync(CorreoWS.Enviar_AdjuntosPreviewRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_ReporteAdjuntoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_ReporteAdjunto", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_ReporteAdjuntoRequestBody Body;

        public Enviar_ReporteAdjuntoRequest()
        {
        }

        public Enviar_ReporteAdjuntoRequest(CorreoWS.Enviar_ReporteAdjuntoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://MSF232.verify/")]
    public partial class Enviar_ReporteAdjuntoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string VALUES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string URL_REPORTE;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string TO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string CC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string BCC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ASUNTO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string CUERPO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string FILENAME;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string PARAMETROS;

        public Enviar_ReporteAdjuntoRequestBody()
        {
        }

        public Enviar_ReporteAdjuntoRequestBody(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string CUERPO, string FILENAME, string PARAMETROS)
        {
            this.VALUES = VALUES;
            this.URL_REPORTE = URL_REPORTE;
            this.TO = TO;
            this.CC = CC;
            this.BCC = BCC;
            this.ASUNTO = ASUNTO;
            this.CUERPO = CUERPO;
            this.FILENAME = FILENAME;
            this.PARAMETROS = PARAMETROS;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_ReporteAdjuntoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_ReporteAdjuntoResponse", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_ReporteAdjuntoResponseBody Body;

        public Enviar_ReporteAdjuntoResponse()
        {
        }

        public Enviar_ReporteAdjuntoResponse(CorreoWS.Enviar_ReporteAdjuntoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Enviar_ReporteAdjuntoResponseBody
    {

        public Enviar_ReporteAdjuntoResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_CorreoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_Correo", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_CorreoRequestBody Body;

        public Enviar_CorreoRequest()
        {
        }

        public Enviar_CorreoRequest(CorreoWS.Enviar_CorreoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://MSF232.verify/")]
    public partial class Enviar_CorreoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string VALUES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string URL_REPORTE;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string TO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string CC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string BCC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ASUNTO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string PARAMETROS;

        public Enviar_CorreoRequestBody()
        {
        }

        public Enviar_CorreoRequestBody(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS)
        {
            this.VALUES = VALUES;
            this.URL_REPORTE = URL_REPORTE;
            this.TO = TO;
            this.CC = CC;
            this.BCC = BCC;
            this.ASUNTO = ASUNTO;
            this.PARAMETROS = PARAMETROS;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_CorreoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_CorreoResponse", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_CorreoResponseBody Body;

        public Enviar_CorreoResponse()
        {
        }

        public Enviar_CorreoResponse(CorreoWS.Enviar_CorreoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Enviar_CorreoResponseBody
    {

        public Enviar_CorreoResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_AdjuntosRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_Adjuntos", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_AdjuntosRequestBody Body;

        public Enviar_AdjuntosRequest()
        {
        }

        public Enviar_AdjuntosRequest(CorreoWS.Enviar_AdjuntosRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://MSF232.verify/")]
    public partial class Enviar_AdjuntosRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string VALUES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string URL_REPORTE;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string TO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string CC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string BCC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ASUNTO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string PARAMETROS;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string NAME_FILES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public CorreoWS.ArrayOfString FILES;

        public Enviar_AdjuntosRequestBody()
        {
        }

        public Enviar_AdjuntosRequestBody(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            this.VALUES = VALUES;
            this.URL_REPORTE = URL_REPORTE;
            this.TO = TO;
            this.CC = CC;
            this.BCC = BCC;
            this.ASUNTO = ASUNTO;
            this.PARAMETROS = PARAMETROS;
            this.NAME_FILES = NAME_FILES;
            this.FILES = FILES;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_AdjuntosResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_AdjuntosResponse", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_AdjuntosResponseBody Body;

        public Enviar_AdjuntosResponse()
        {
        }

        public Enviar_AdjuntosResponse(CorreoWS.Enviar_AdjuntosResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Enviar_AdjuntosResponseBody
    {

        public Enviar_AdjuntosResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_AdjuntosPreviewRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_AdjuntosPreview", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_AdjuntosPreviewRequestBody Body;

        public Enviar_AdjuntosPreviewRequest()
        {
        }

        public Enviar_AdjuntosPreviewRequest(CorreoWS.Enviar_AdjuntosPreviewRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://MSF232.verify/")]
    public partial class Enviar_AdjuntosPreviewRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string VALUES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string URL_REPORTE;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string TO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string CC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string BCC;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ASUNTO;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string PARAMETROS;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string NAME_FILES;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public CorreoWS.ArrayOfString FILES;

        public Enviar_AdjuntosPreviewRequestBody()
        {
        }

        public Enviar_AdjuntosPreviewRequestBody(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            this.VALUES = VALUES;
            this.URL_REPORTE = URL_REPORTE;
            this.TO = TO;
            this.CC = CC;
            this.BCC = BCC;
            this.ASUNTO = ASUNTO;
            this.PARAMETROS = PARAMETROS;
            this.NAME_FILES = NAME_FILES;
            this.FILES = FILES;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Enviar_AdjuntosPreviewResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Enviar_AdjuntosPreviewResponse", Namespace = "http://MSF232.verify/", Order = 0)]
        public CorreoWS.Enviar_AdjuntosPreviewResponseBody Body;

        public Enviar_AdjuntosPreviewResponse()
        {
        }

        public Enviar_AdjuntosPreviewResponse(CorreoWS.Enviar_AdjuntosPreviewResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Enviar_AdjuntosPreviewResponseBody
    {

        public Enviar_AdjuntosPreviewResponseBody()
        {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceSoapChannel : CorreoWS.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CorreoWS.WebServiceSoap>, CorreoWS.WebServiceSoap
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) :
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public WebServiceSoapClient()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorreoWS.Enviar_ReporteAdjuntoResponse CorreoWS.WebServiceSoap.Enviar_ReporteAdjunto(CorreoWS.Enviar_ReporteAdjuntoRequest request)
        {
            return base.Channel.Enviar_ReporteAdjunto(request);
        }

        public void Enviar_ReporteAdjunto(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string CUERPO, string FILENAME, string PARAMETROS)
        {
            CorreoWS.Enviar_ReporteAdjuntoRequest inValue = new CorreoWS.Enviar_ReporteAdjuntoRequest();
            inValue.Body = new CorreoWS.Enviar_ReporteAdjuntoRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.CUERPO = CUERPO;
            inValue.Body.FILENAME = FILENAME;
            inValue.Body.PARAMETROS = PARAMETROS;
            CorreoWS.Enviar_ReporteAdjuntoResponse retVal = ((CorreoWS.WebServiceSoap)(this)).Enviar_ReporteAdjunto(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CorreoWS.Enviar_ReporteAdjuntoResponse> CorreoWS.WebServiceSoap.Enviar_ReporteAdjuntoAsync(CorreoWS.Enviar_ReporteAdjuntoRequest request)
        {
            return base.Channel.Enviar_ReporteAdjuntoAsync(request);
        }

        public System.Threading.Tasks.Task<CorreoWS.Enviar_ReporteAdjuntoResponse> Enviar_ReporteAdjuntoAsync(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string CUERPO, string FILENAME, string PARAMETROS)
        {
            CorreoWS.Enviar_ReporteAdjuntoRequest inValue = new CorreoWS.Enviar_ReporteAdjuntoRequest();
            inValue.Body = new CorreoWS.Enviar_ReporteAdjuntoRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.CUERPO = CUERPO;
            inValue.Body.FILENAME = FILENAME;
            inValue.Body.PARAMETROS = PARAMETROS;
            return ((CorreoWS.WebServiceSoap)(this)).Enviar_ReporteAdjuntoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorreoWS.Enviar_CorreoResponse CorreoWS.WebServiceSoap.Enviar_Correo(CorreoWS.Enviar_CorreoRequest request)
        {
            return base.Channel.Enviar_Correo(request);
        }

        public void Enviar_Correo(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS)
        {
            CorreoWS.Enviar_CorreoRequest inValue = new CorreoWS.Enviar_CorreoRequest();
            inValue.Body = new CorreoWS.Enviar_CorreoRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            CorreoWS.Enviar_CorreoResponse retVal = ((CorreoWS.WebServiceSoap)(this)).Enviar_Correo(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CorreoWS.Enviar_CorreoResponse> CorreoWS.WebServiceSoap.Enviar_CorreoAsync(CorreoWS.Enviar_CorreoRequest request)
        {
            return base.Channel.Enviar_CorreoAsync(request);
        }

        public System.Threading.Tasks.Task<CorreoWS.Enviar_CorreoResponse> Enviar_CorreoAsync(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS)
        {
            CorreoWS.Enviar_CorreoRequest inValue = new CorreoWS.Enviar_CorreoRequest();
            inValue.Body = new CorreoWS.Enviar_CorreoRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            return ((CorreoWS.WebServiceSoap)(this)).Enviar_CorreoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorreoWS.Enviar_AdjuntosResponse CorreoWS.WebServiceSoap.Enviar_Adjuntos(CorreoWS.Enviar_AdjuntosRequest request)
        {
            return base.Channel.Enviar_Adjuntos(request);
        }

        public void Enviar_Adjuntos(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            CorreoWS.Enviar_AdjuntosRequest inValue = new CorreoWS.Enviar_AdjuntosRequest();
            inValue.Body = new CorreoWS.Enviar_AdjuntosRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            inValue.Body.NAME_FILES = NAME_FILES;
            inValue.Body.FILES = FILES;
            CorreoWS.Enviar_AdjuntosResponse retVal = ((CorreoWS.WebServiceSoap)(this)).Enviar_Adjuntos(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosResponse> CorreoWS.WebServiceSoap.Enviar_AdjuntosAsync(CorreoWS.Enviar_AdjuntosRequest request)
        {
            return base.Channel.Enviar_AdjuntosAsync(request);
        }

        public System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosResponse> Enviar_AdjuntosAsync(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            CorreoWS.Enviar_AdjuntosRequest inValue = new CorreoWS.Enviar_AdjuntosRequest();
            inValue.Body = new CorreoWS.Enviar_AdjuntosRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            inValue.Body.NAME_FILES = NAME_FILES;
            inValue.Body.FILES = FILES;
            return ((CorreoWS.WebServiceSoap)(this)).Enviar_AdjuntosAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CorreoWS.Enviar_AdjuntosPreviewResponse CorreoWS.WebServiceSoap.Enviar_AdjuntosPreview(CorreoWS.Enviar_AdjuntosPreviewRequest request)
        {
            return base.Channel.Enviar_AdjuntosPreview(request);
        }

        public void Enviar_AdjuntosPreview(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            CorreoWS.Enviar_AdjuntosPreviewRequest inValue = new CorreoWS.Enviar_AdjuntosPreviewRequest();
            inValue.Body = new CorreoWS.Enviar_AdjuntosPreviewRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            inValue.Body.NAME_FILES = NAME_FILES;
            inValue.Body.FILES = FILES;
            CorreoWS.Enviar_AdjuntosPreviewResponse retVal = ((CorreoWS.WebServiceSoap)(this)).Enviar_AdjuntosPreview(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosPreviewResponse> CorreoWS.WebServiceSoap.Enviar_AdjuntosPreviewAsync(CorreoWS.Enviar_AdjuntosPreviewRequest request)
        {
            return base.Channel.Enviar_AdjuntosPreviewAsync(request);
        }

        public System.Threading.Tasks.Task<CorreoWS.Enviar_AdjuntosPreviewResponse> Enviar_AdjuntosPreviewAsync(string VALUES, string URL_REPORTE, string TO, string CC, string BCC, string ASUNTO, string PARAMETROS, string NAME_FILES, CorreoWS.ArrayOfString FILES)
        {
            CorreoWS.Enviar_AdjuntosPreviewRequest inValue = new CorreoWS.Enviar_AdjuntosPreviewRequest();
            inValue.Body = new CorreoWS.Enviar_AdjuntosPreviewRequestBody();
            inValue.Body.VALUES = VALUES;
            inValue.Body.URL_REPORTE = URL_REPORTE;
            inValue.Body.TO = TO;
            inValue.Body.CC = CC;
            inValue.Body.BCC = BCC;
            inValue.Body.ASUNTO = ASUNTO;
            inValue.Body.PARAMETROS = PARAMETROS;
            inValue.Body.NAME_FILES = NAME_FILES;
            inValue.Body.FILES = FILES;
            return ((CorreoWS.WebServiceSoap)(this)).Enviar_AdjuntosPreviewAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.51.64.37/CORREOS_PBI/WebService.asmx");
            }

            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            WebServiceSoap,

        }
    }
}
